### ISSUE TITLE
Handle the 979 ISBN-13 prefix

### ISSUE THREAD

**Issue by neilmayhew** [charukiewicz/hs-isbn#1]
According to Wikipedia:

> for a 13-digit ISBN, a prefix element – a GS1 prefix: so far 978 or 979 have been made available by GS1,

> As the 978 ISBN supply is exhausted, the 979 prefix was introduced.

> The registration group identifiers within prefix element 979 that have been assigned are 8 for the United States of America, 10 for France, 11 for the Republic of Korea, and 12 for Italy.

So it seems that 979 is a thing, even though ISBNs using it may still be rare in the wild.

**Comment by charukiewicz** [comment]
Hi @neilmayhew. Thanks for pointing this out. Are 979-prefix ISBN-13s not being handled correctly somewhere? I'm testing this in my repl:

```
> validateISBN "9791096315390"
Right (ISBN13 "9791096315390")
> calculateISBN13CheckDigitValue "979109631539"
0
```

I checked whether this may be an issue for conversion between ISBN-10 and ISBN-13, but it looks like only 978 prefixed ISBN-13s can be converted. Here's what the Wikipedia article says:

> An ISBN-10 is converted to ISBN-13 by prepending "978" to the ISBN-10 and recalculating the final checksum digit using the ISBN-13 algorithm. The reverse process can also be performed, but not for numbers commencing with a prefix other than 978, which have no 10-digit equivalent.

Please let me know if I am missing something.

**Comment by neilmayhew** [comment]
Sorry, yes, you're right. It's only an issue in 10/13 conversion, and of course it couldn't be anything other than 978 there because when you start with a 10 there can be only one hardcoded prefix. Also, I didn't spot that text in the Wikipedia page.

I read through your code, noticed there was some hardcoded use of 978, and read the WP page afterwards. I was surprised to see mention of 979 and mistakenly assumed it was an issue without checking back.

Sorry for the wasted time and effort! Thanks for writing this library and making it available to others.

**Comment by charukiewicz** [comment]
No problem at all! I appreciate you taking the time to look through the code and taking the time to write this issue.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by neilmayhew** [comment]
You're welcome.

While I have your attention, maybe I could mention one other thing that's too small to warrant its own issue. It would be helpful to discuss in the documentation somewhere (maybe in the README) the reasons behind the design decision of using `Text` for the internal representation vs some other alternatives such as `Int64` or `ShortByteString` (since the allowed characters are all in the ASCII range). I think `Text` is a perfectly reasonable choice, but like all choices it's a tradeoff that reflects the expected use cases, and I think it would be useful to spell these out.

**Comment by charukiewicz** [comment]
Thanks for the feedback. I will say that your feedback isn't the only one that I got about the internal representation of `ISBN`, so I think discussing it warrants a new issue. I just opened #2 if you'd like to take a look and move the discussion there.
